# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('manufactured', models.DateField()),
                ('classification', models.CharField(
                    blank=True,
                    choices=[
                        ('SEDAN', 'Sedan'),
                        ('HATCH', 'Hatchback'),
                        ('TRUCK', 'Truck'),
                        ('VAN', 'Van'),
                        ('CONVERT', 'Convertible'),
                        ('SPORT', 'Sport'),
                    ],
                    max_length=10
                )),
                ('retail_price', models.DecimalField(decimal_places=4, default=0, max_digits=11)),
                ('is_bullet_proof', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.Manufacturer'),
        ),
    ]
